version: '3'
services:
  api_gateway:
    build: ./api_gateway
    environment:
      - PORT=8000
    ports:
      - "80:8000"
    depends_on:
      - user_service
      - booking_service
      - commBoard_service
      - marketPlace_service
      - workOrder_service
      - notification_service
    #healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
  
  user_service:
    build: ./user_service
    # No ports exposed to the host, only accessible within the Docker network
  
  booking_service:
    build: ./booking_service
  
  commBoard_service:
    build: ./commBoard_service

  marketPlace_service:
    build: ./marketPlace_service

  workOrder_service:
    build: ./workOrder_service

  notification_service:
    build: ./notification_service

