version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  apigateway: #denotes the service name that Docker Compose will use when creating containers
    build: .
    ports:
      - "3000:3000"
    environment:
      - KAFKA_BROKER_LIST=kafka:9092
    depends_on:
      - kafka
    command: npm start
